[package]
name = "learning_rust"
version = "0.1.0"
authors = ["csunny <cfqsunny@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
rand = "0.3.14"


